version: "3.6"

services:
  frontend:
    build: ./example-frontend
    ports:
      - "127.0.0.1:7070:7070"
    environment:
      - REACT_APP_BACKEND_URL=backend
    networks:
      - app-network

  backend:
    build: ./example-backend
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:7070
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

networks:
  app-network:
