version: "3.6"

services:
  frontend:
    build: ./example-frontend
    networks:
      - app-network

  backend:
    build: ./example-backend
    environment:
      - REQUEST_ORIGIN=http://frontend
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
      - db
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
